
export type Language = 'en' | 'tr' | 'es' | 'fr' | 'ar' | 'hi' | 'bn' | 'ru' | 'pt' | 'id';

export const languages: { name: string; code: Language }[] = [
    { name: "English", code: "en" },
    { name: "Türkçe", code: "tr" },
    { name: "Español", code: "es" },
    { name: "Français", code: "fr" },
    { name: "العربية", code: "ar" },
    { name: "हिन्दी", code: "hi" },
    { name: "বাংলা", code: "bn" },
    { name: "Русский", code: "ru" },
    { name: "Português", code: "pt" },
    { name: "Bahasa Indonesia", code: "id" },
];

const en = {
    home: 'Home',
    explore: 'Explore',
    notifications: 'Notifications',
    profile: 'Profile',
    createPost: 'Create Post',
    settings: 'Settings',
    appearance: 'Appearance',
    toggleTheme: 'Toggle theme',
    colorTheme: 'Color Theme',
    language: 'Language',
    logout: 'Logout',
    whatsOnYourMind: "What's on your mind?",
    selectImageToUpload: 'Select an image to upload',
    selectVideoToUpload: 'Select a video to upload',
    post: 'Post',
    posting: 'Posting...',
    linkUrlPlaceholder: 'Enter link to share',
    save: 'Save',
    saved: 'Saved',
    reportPost: 'Report Post',
    reportDescription: 'Please provide a reason for reporting this post. Your feedback is important for community safety.',
    reportPlaceholder: 'e.g., spam, inappropriate content, harassment...',
    cancel: 'Cancel',
    submitReport: 'Submit Report',
    deletePost: 'Delete Post',
    createNewPost: 'Create a new post',
};

const tr: typeof en = {
    home: 'Anasayfa',
    explore: 'Keşfet',
    notifications: 'Bildirimler',
    profile: 'Profil',
    createPost: 'Gönderi Oluştur',
    settings: 'Ayarlar',
    appearance: 'Görünüm',
    toggleTheme: 'Temayı değiştir',
    colorTheme: 'Renk Teması',
    language: 'Dil',
    logout: 'Çıkış Yap',
    whatsOnYourMind: 'Aklında ne var?',
    selectImageToUpload: 'Yüklenecek bir resim seçin',
    selectVideoToUpload: 'Yüklenecek bir video seçin',
    post: 'Gönder',
    posting: 'Gönderiliyor...',
    linkUrlPlaceholder: 'Paylaşılacak bağlantıyı girin',
    save: 'Kaydet',
    saved: 'Kaydedildi',
    reportPost: 'Gönderiyi Bildir',
    reportDescription: 'Lütfen bu gönderiyi bildirmek için bir neden belirtin. Geri bildiriminiz topluluk güvenliği için önemlidir.',
    reportPlaceholder: 'örn. spam, uygunsuz içerik, taciz...',
    cancel: 'İptal',
    submitReport: 'Raporu Gönder',
    deletePost: 'Gönderiyi Sil',
    createNewPost: 'Yeni bir gönderi oluştur',
};

const es: typeof en = {
    home: 'Inicio',
    explore: 'Explorar',
    notifications: 'Notificaciones',
    profile: 'Perfil',
    createPost: 'Crear Publicación',
    settings: 'Ajustes',
    appearance: 'Apariencia',
    toggleTheme: 'Cambiar tema',
    colorTheme: 'Tema de color',
    language: 'Idioma',
    logout: 'Cerrar Sesión',
    whatsOnYourMind: '¿Qué estás pensando?',
    selectImageToUpload: 'Selecciona una imagen para subir',
    selectVideoToUpload: 'Selecciona un video para subir',
    post: 'Publicar',
    posting: 'Publicando...',
    linkUrlPlaceholder: 'Ingresa el enlace para compartir',
    save: 'Guardar',
    saved: 'Guardado',
    reportPost: 'Reportar Publicación',
    reportDescription: 'Por favor, proporciona una razón para reportar esta publicación. Tus comentarios son importantes para la seguridad de la comunidad.',
    reportPlaceholder: 'ej. spam, contenido inapropiado, acoso...',
    cancel: 'Cancelar',
    submitReport: 'Enviar Reporte',
    deletePost: 'Eliminar Publicación',
    createNewPost: 'Crear una nueva publicación',
};

const fr: typeof en = {
    home: 'Accueil',
    explore: 'Explorer',
    notifications: 'Notifications',
    profile: 'Profil',
    createPost: 'Créer une publication',
    settings: 'Paramètres',
    appearance: 'Apparence',
    toggleTheme: 'Changer de thème',
    colorTheme: 'Thème de couleur',
    language: 'Langue',
    logout: 'Se déconnecter',
    whatsOnYourMind: 'À quoi pensez-vous ?',
    selectImageToUpload: 'Sélectionnez une image à télécharger',
    selectVideoToUpload: 'Sélectionnez une vidéo à télécharger',
    post: 'Publier',
    posting: 'Publication...',
    linkUrlPlaceholder: 'Entrez le lien à partager',
    save: 'Enregistrer',
    saved: 'Enregistré',
    reportPost: 'Signaler la publication',
    reportDescription: 'Veuillez fournir une raison pour signaler cette publication. Vos commentaires sont importants pour la sécurité de la communauté.',
    reportPlaceholder: 'par ex. spam, contenu inapproprié, harcèlement...',
    cancel: 'Annuler',
    submitReport: 'Soumettre le signalement',
    deletePost: 'Supprimer la publication',
    createNewPost: 'Créer une nouvelle publication',
};

const ar: typeof en = {
    home: 'الرئيسية',
    explore: 'استكشف',
    notifications: 'الإشعارات',
    profile: 'الملف الشخصي',
    createPost: 'إنشاء منشور',
    settings: 'الإعدادات',
    appearance: 'المظهر',
    toggleTheme: 'تبديل السمة',
    colorTheme: 'سمة اللون',
    language: 'اللغة',
    logout: 'تسجيل الخروج',
    whatsOnYourMind: 'بماذا تفكر؟',
    selectImageToUpload: 'اختر صورة للتحميل',
    selectVideoToUpload: 'اختر فيديو للتحميل',
    post: 'نشر',
    posting: 'جارٍ النشر...',
    linkUrlPlaceholder: 'أدخل الرابط للمشاركة',
    save: 'حفظ',
    saved: 'محفوظ',
    reportPost: 'الإبلاغ عن المنشور',
    reportDescription: 'يرجى تقديم سبب للإبلاغ عن هذا المنشور. ملاحظاتك مهمة لسلامة المجتمع.',
    reportPlaceholder: 'مثال: بريد مزعج، محتوى غير لائق، مضايقة...',
    cancel: 'إلغاء',
    submitReport: 'إرسال البلاغ',
    deletePost: 'حذف المنشور',
    createNewPost: 'إنشاء منشور جديد',
};

const hi: typeof en = {
    home: 'होम',
    explore: 'अन्वेषण करें',
    notifications: 'सूचनाएं',
    profile: 'प्रोफ़ाइल',
    createPost: 'पोस्ट बनाएं',
    settings: 'सेटिंग्स',
    appearance: 'दिखावट',
    toggleTheme: 'थीम बदलें',
    colorTheme: 'रंग थीम',
    language: 'भाषा',
    logout: 'लॉग आउट',
    whatsOnYourMind: 'आपके मन में क्या है?',
    selectImageToUpload: 'अपलोड करने के लिए एक छवि चुनें',
    selectVideoToUpload: 'अपलोड करने के लिए एक वीडियो चुनें',
    post: 'पोस्ट करें',
    posting: 'पोस्ट किया जा रहा है...',
    linkUrlPlaceholder: 'साझा करने के लिए लिंक दर्ज करें',
    save: 'सहेजें',
    saved: 'सहेजा गया',
    reportPost: 'पोस्ट की रिपोर्ट करें',
    reportDescription: 'कृपया इस पोस्ट की रिपोर्ट करने का कारण बताएं। आपकी प्रतिक्रिया समुदाय की सुरक्षा के लिए महत्वपूर्ण है।',
    reportPlaceholder: 'उदा. स्पैम, अनुचित सामग्री, उत्पीड़न...',
    cancel: 'रद्द करें',
    submitReport: 'रिपोर्ट सबमिट करें',
    deletePost: 'पोस्ट हटाएं',
    createNewPost: 'एक नई पोस्ट बनाएं',
};

const bn: typeof en = {
    home: 'হোম',
    explore: 'অন্বেষণ',
    notifications: 'বিজ্ঞপ্তি',
    profile: 'প্রোফাইল',
    createPost: 'পোস্ট তৈরি করুন',
    settings: 'সেটিংস',
    appearance: 'চেহারা',
    toggleTheme: 'থিম পরিবর্তন করুন',
    colorTheme: 'রঙের থিম',
    language: 'ভাষা',
    logout: 'লগ আউট',
    whatsOnYourMind: 'আপনার মনে কি আছে?',
    selectImageToUpload: 'আপলোড করার জন্য একটি ছবি নির্বাচন করুন',
    selectVideoToUpload: 'আপলোড করার জন্য একটি ভিডিও নির্বাচন করুন',
    post: 'পোস্ট করুন',
    posting: 'পোস্ট করা হচ্ছে...',
    linkUrlPlaceholder: 'শেয়ার করার জন্য লিঙ্ক লিখুন',
    save: 'সংরক্ষণ',
    saved: 'সংরক্ষিত',
    reportPost: 'পোস্ট রিপোর্ট করুন',
    reportDescription: 'এই পোস্টটি রিপোর্ট করার একটি কারণ প্রদান করুন। আপনার মতামত সম্প্রদায়ের সুরক্ষার জন্য গুরুত্বপূর্ণ।',
    reportPlaceholder: 'যেমন স্প্যাম, অনুপযুক্ত বিষয়বস্তু, হয়রানি...',
    cancel: 'বাতিল করুন',
    submitReport: 'রিপোর্ট জমা দিন',
    deletePost: 'পোস্ট মুছুন',
    createNewPost: 'একটি নতুন পোস্ট তৈরি করুন',
};

const ru: typeof en = {
    home: 'Главная',
    explore: 'Исследовать',
    notifications: 'Уведомления',
    profile: 'Профиль',
    createPost: 'Создать пост',
    settings: 'Настройки',
    appearance: 'Внешний вид',
    toggleTheme: 'Сменить тему',
    colorTheme: 'Цветовая тема',
    language: 'Язык',
    logout: 'Выйти',
    whatsOnYourMind: 'О чем вы думаете?',
    selectImageToUpload: 'Выберите изображение для загрузки',
    selectVideoToUpload: 'Выберите видео для загрузки',
    post: 'Опубликовать',
    posting: 'Публикация...',
    linkUrlPlaceholder: 'Введите ссылку, чтобы поделиться',
    save: 'Сохранить',
    saved: 'Сохранено',
    reportPost: 'Пожаловаться на публикацию',
    reportDescription: 'Пожалуйста, укажите причину жалобы на эту публикацию. Ваш отзыв важен для безопасности сообщества.',
    reportPlaceholder: 'например, спам, неприемлемый контент, преследование...',
    cancel: 'Отмена',
    submitReport: 'Отправить жалобу',
    deletePost: 'Удалить публикацию',
    createNewPost: 'Создать новую публикацию',
};

const pt: typeof en = {
    home: 'Início',
    explore: 'Explorar',
    notifications: 'Notificações',
    profile: 'Perfil',
    createPost: 'Criar Publicação',
    settings: 'Configurações',
    appearance: 'Aparência',
    toggleTheme: 'Alternar tema',
    colorTheme: 'Tema de Cores',
    language: 'Idioma',
    logout: 'Sair',
    whatsOnYourMind: 'No que você está pensando?',
    selectImageToUpload: 'Selecione uma imagem para enviar',
    selectVideoToUpload: 'Selecione um vídeo para enviar',
    post: 'Publicar',
    posting: 'Publicando...',
    linkUrlPlaceholder: 'Digite o link para compartilhar',
    save: 'Salvar',
    saved: 'Salvo',
    reportPost: 'Denunciar Publicação',
    reportDescription: 'Por favor, forneça um motivo para denunciar esta publicação. Seu feedback é importante para a segurança da comunidade.',
    reportPlaceholder: 'por exemplo, spam, conteúdo impróprio, assédio...',
    cancel: 'Cancelar',
    submitReport: 'Enviar Denúncia',
    deletePost: 'Excluir Publicação',
    createNewPost: 'Criar uma nova publicação',
};

const id: typeof en = {
    home: 'Beranda',
    explore: 'Jelajahi',
    notifications: 'Notifikasi',
    profile: 'Profil',
    createPost: 'Buat Postingan',
    settings: 'Pengaturan',
    appearance: 'Tampilan',
    toggleTheme: 'Ganti tema',
    colorTheme: 'Tema Warna',
    language: 'Bahasa',
    logout: 'Keluar',
    whatsOnYourMind: 'Apa yang ada di pikiranmu?',
    selectImageToUpload: 'Pilih gambar untuk diunggah',
    selectVideoToUpload: 'Pilih video untuk diunggah',
    post: 'Kirim',
    posting: 'Mengirim...',
    linkUrlPlaceholder: 'Masukkan tautan untuk dibagikan',
    save: 'Simpan',
    saved: 'Disimpan',
    reportPost: 'Laporkan Postingan',
    reportDescription: 'Harap berikan alasan untuk melaporkan postingan ini. Umpan balik Anda penting untuk keamanan komunitas.',
    reportPlaceholder: 'misalnya, spam, konten tidak pantas, pelecehan...',
    cancel: 'Batal',
    submitReport: 'Kirim Laporan',
    deletePost: 'Hapus Postingan',
    createNewPost: 'Buat postingan baru',
};


export const appStrings = {
    en,
    tr,
    es,
    fr,
    ar,
    hi,
    bn,
    ru,
    pt,
    id,
};

export type AppStrings = typeof appStrings;

    
